# 项目全局配置文件

# 应用配置
app:
  name: "PDF智能文件管理系统"
  version: "1.0.0"
  debug: false  # 关闭debug模式，避免与PaddleOCR冲突
  host: "0.0.0.0"
  port: 5002

# 文件上传配置
upload:
  # 文件保存目录
  upload_dir: "uploads"
  # 允许的文件扩展名
  allowed_extensions: [".pdf"]
  # 最大文件大小 (MB)
  max_file_size: 100

# 多媒体内容配置
multimedia:
  # 图片保存配置
  images:
    # 图片保存目录
    save_dir: "uploads/images"
    # 支持的图片格式
    supported_formats: [".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff"]
    # 图片质量压缩（1-100，100为最高质量）
    compression_quality: 85
    # 最大图片尺寸（像素）
    max_width: 2048
    max_height: 2048
    # 是否保留原始图片
    keep_original: true
  
  # 表格导出配置
  tables:
    # 表格导出目录
    export_dir: "uploads/tables"
    # 支持的导出格式
    export_formats: ["csv", "xlsx", "json"]
    # 表格显示最大行数
    max_display_rows: 100
  
  # 图表保存配置
  charts:
    # 图表保存目录
    save_dir: "uploads/charts"
    # 图表渲染格式
    render_formats: ["png", "svg", "pdf"]
    # 图表分辨率（DPI）
    dpi: 300
  
# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  

# GraphRAG配置
graph_rag:
  # 文本块大小
  chunk_size: 1000
  # 文本块重叠
  chunk_overlap: 200
  # 实体提取阈值
  entity_threshold: 0.8
  # 关系提取阈值
  relation_threshold: 0.7
  
  # 多模态内容处理配置
  multimodal:
    # 图像处理配置
    image_processing:
      enabled: true
      # 图像理解模型
      understanding_model: "blip2"
      # 图像描述最大长度
      max_description_length: 500
      # 是否保存图像到文件系统
      save_to_filesystem: true
      # 图像压缩质量
      compression_quality: 85
    
    # 表格处理配置
    table_processing:
      enabled: true
      # 表格检测模型
      detection_model: "table-transformer"
      # 表格内容最大行数（用于嵌入）
      max_embed_rows: 50
      # 是否保留完整表格数据
      keep_full_table: true
      # 表格摘要生成
      generate_summary: true
    
    # 图表处理配置
    chart_processing:
      enabled: true
      # 图表类型检测
      type_detection: true
      # 数据点提取
      data_extraction: true
      # 趋势分析
      trend_analysis: true
      # 图表描述生成
      description_generation: true
  
  # 批处理配置
  batch_processing:
    enabled: true
    default_batch_size: 2
    max_batch_size: 8
    min_batch_size: 1
    
  # 知识图谱配置
  knowledge_graph:
    # 实体去重策略
    entity_deduplication: "name_similarity"
    # 相似度阈值（用于实体合并）
    similarity_threshold: 0.85
    # 关系推理
    relation_inference: true
    # 图谱优化
    graph_optimization: true
  
# 向量检索配置
vector_search:
  # 检索结果数量
  top_k: 5
  # 相似度阈值
  similarity_threshold: 0.7
  
# 图检索配置
graph_search:
  # 最大跳数
  max_hops: 3
  # 路径数量限制
  max_paths: 10 

# 内存和GPU优化配置
optimization:
  # 内存优化
  memory:
    gc_threshold: 85  # 内存使用率超过85%时触发垃圾回收
    model_unload_threshold: 90  # 内存使用率超过90%时卸载模型
  # GPU优化
  gpu:
    memory_fraction: 0.8  # GPU显存使用比例
    allow_growth: true    # 允许显存动态增长
# 错误处理和恢复
error_handling:
  # 最大重试次数
  max_retries: 3
  # 重试间隔（秒）
  retry_interval: 5
  # 失败回退策略
  fallback_strategy: "conservative"  # conservative, disable, retry
  # 错误上报
  error_reporting:
    enabled: true
    include_stack_trace: true
    
# 开发和调试配置
development:
  # 启用开发模式
  debug_mode: false  # 改为false，避免与AI模型冲突
  # 详细日志
  verbose_logging: true

  # 模型预加载（开发时建议禁用，避免debug冲突）
  preload_models: true
  # 开发环境特殊设置
  dev_mode_safe: true  # 启用开发安全模式，禁用可能冲突的功能
  # 启用图像OCR识别功能 - 针对装修合同等图像型PDF优化
  skip_image_ocr: false  # 开启OCR功能，支持图像文字识别
  # OCR性能优化
  ocr_timeout: 15  # 增加OCR超时时间
  max_image_size: 30000000  # 增加图像处理大小限制（3M像素）