# 模型配置文件 - 管理项目中使用的所有模型

# 全局GPU加速开关，true为启用GPU，false为使用CPU
gpu_acceleration: true

# 大语言模型配置 - 使用DeepSeek API
llm:
  type: "deepseek"
  api_url: "https://api.deepseek.com"
  api_key: "sk-27e712e3a6c64533884adc0ad040ff3b"
  model_name: "deepseek-chat"
  max_tokens: 4096
  temperature: 0.7

# 嵌入模型配置 - 768维本地模型
embedding:
  model_name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"  # 768维多语言嵌入模型
  model_path: "models/embedding"
  dimensions: 768
  max_length: 512
  
# OCR模型配置 - 使用PaddleOCR
ocr:
  # 使用PaddleOCR作为唯一OCR引擎
  engine: "paddleocr"
  
  # PaddleOCR配置
  model_name: "paddleocr"
  model_path: "models/ocr"
  language: ["ch", "en"]  # 支持中英文
  use_angle_cls: true     # 使用角度分类器
  use_gpu: true          # 根据gpu_acceleration全局控制自动调整
  
  # PaddleOCR检测参数
  detection_params:
    det_limit_side_len: 960     # 检测模型输入图像长边限制
    det_limit_type: "max"       # 检测模型输入图像限制类型
    det_thresh: 0.3            # 检测阈值
    det_box_thresh: 0.6        # 检测框阈值
    det_unclip_ratio: 1.5      # 检测框扩展比例
    max_candidates: 1000       # 最大候选框数量
    unclip_ratio: 1.5          # 文本框扩展比例
    use_polygon: false         # 是否使用多边形检测
  
  # PaddleOCR识别参数  
  recognition_params:
    rec_batch_num: 6           # 识别批处理大小
    max_text_length: 25        # 最大文本长度
    rec_char_dict_path: ""     # 字典路径（空则使用默认）
    use_space_char: true       # 是否使用空格字符
  
# 表格检测模型
table_detection:
  model_name: "microsoft/table-transformer-detection"
  model_path: "models/table_detection"
  # 检测阈值
  detection_threshold: 0.7
  # 最大表格数量（每页）
  max_tables_per_page: 10
  # 表格内容提取
  content_extraction:
    enabled: true
    # 使用OCR提取表格文本
    use_ocr: true
    # 表格结构识别
    structure_recognition: true
  
# 图像分析模型
image_analysis:
  model_name: "Salesforce/blip2-opt-2.7b"
  model_path: "models/image_analysis"
  # 图像理解配置
  understanding:
    # 描述生成
    description_generation: true
    # 对象检测
    object_detection: true
    # 场景理解
    scene_understanding: true
    # 文字检测（配合OCR）
    text_detection: true
  # 处理参数
  processing:
    # 最大输入分辨率
    max_resolution: [1024, 1024]
    # 批处理大小
    batch_size: 1
    # 生成参数
    generation:
      max_length: 200
      temperature: 0.7
      do_sample: true

# 图表识别模型  
chart_recognition:
  model_name: "ahmed-masry/chartqa_with_t5"
  model_path: "models/chart_recognition"
  # 图表类型支持
  supported_chart_types:
    - "bar_chart"
    - "line_chart"
    - "pie_chart"
    - "scatter_plot"
    - "histogram"
    - "box_plot"
    - "area_chart"
  # 数据提取配置
  data_extraction:
    # 坐标轴识别
    axis_recognition: true
    # 数据点提取
    data_point_extraction: true
    # 趋势分析
    trend_analysis: true
    # 统计信息
    statistical_analysis: true
  # 描述生成
  description_generation:
    # 结构化描述
    structured_description: true
    # 自然语言描述
    natural_language_description: true
    # 数据摘要
    data_summary: true

# NER模型配置 - 新增优化功能
ner:
  # spaCy模型配置
  spacy:
    # 中文模型
    zh_model: "zh_core_web_sm"
    # 英文模型
    en_model: "en_core_web_sm"
    # 自动下载
    auto_download: true
    # 模型路径
    model_path: "models/ner/spacy"
  
  # jieba分词配置
  jieba:
    # 用户词典路径
    user_dict_path: "models/ner/jieba/user_dict.txt"
    # 自定义分词规则
    custom_rules: true
    # 模型路径
    model_path: "models/ner/jieba"
  
  # 实体类型配置
  entity_types:
    - "PERSON"      # 人名
    - "ORG"         # 组织
    - "GPE"         # 地理政治实体
    - "MONEY"       # 货币
    - "DATE"        # 日期
    - "TIME"        # 时间
    - "PERCENT"     # 百分比
    - "PRODUCT"     # 产品
    - "EVENT"       # 事件

# 重排序模型配置 - 新增优化功能
reranking:
  # 默认重排序算法
  default_algorithm: "RRF"  # RRF, BGE-reranker, Mini-LM
  
  # RRF算法配置
  rrf:
    k: 60  # RRF参数
    enabled: true
  
  # BGE重排序模型
  bge_reranker:
    model_name: "BAAI/bge-reranker-base"
    model_path: "models/reranking/bge_reranker"
    enabled: false
    max_length: 512
    batch_size: 16
  
  # MiniLM重排序模型
  mini_lm:
    model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_path: "models/reranking/mini_lm"
    enabled: false
    max_length: 512
    batch_size: 16
  
  # 通用CrossEncoder配置
  cross_encoder:
    models:
      - "BAAI/bge-reranker-base"
      - "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_path: "models/reranking"
    auto_download: true

# 多模态处理模型配置 - 新增优化功能
multimodal:
  # 图像处理配置
  image_processing:
    # 预处理参数
    preprocessing:
      resize_mode: "maintain_aspect_ratio"
      max_size: [1024, 1024]
      normalize: true
    
    # 特征提取
    feature_extraction:
      model_name: "openai/clip-vit-base-patch32"
      model_path: "models/multimodal/clip"
      enabled: true
  
  # 表格分析增强
  table_analysis:
    # 结构识别模型
    structure_model:
      model_name: "microsoft/table-transformer-structure-recognition"
      model_path: "models/multimodal/table_structure"
    
    # 内容提取增强
    content_extraction:
      use_deep_learning: true
      ocr_integration: true
  
  # 图表分析增强
  chart_analysis:
    analysis_models:
      # 表格分析模型
      table:
        model_name: "microsoft/table-transformer-structure-recognition"
        model_path: "models/multimodal/table"
      
      # 图表分析模型  
      chart:
        model_name: "google/deplot"
        model_path: "models/multimodal/chart"
    
    # 数据提取增强
    data_extraction:
      coordinate_detection: true
      value_extraction: true
      trend_analysis: true


# 模型下载地址配置
model_downloads:
  embedding:
    url: "https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
    auto_download: true
    cache_dir: "models/embedding"
  
  ocr:
    # PaddleOCR模型配置
    paddleocr:
      auto_download: true
      cache_dir: "models/ocr"
      
  table_detection:
    url: "https://huggingface.co/microsoft/table-transformer-detection"
    auto_download: true
    cache_dir: "models/table_detection"
    
  image_analysis:
    url: "https://huggingface.co/Salesforce/blip2-opt-2.7b"
    auto_download: true
    cache_dir: "models/image_analysis"
    # 替代模型（如果主模型不可用）
    fallback_models:
      - "Salesforce/blip2-flan-t5-xl"
      - "microsoft/DiT-base"
      
  chart_recognition:
    url: "https://huggingface.co/ahmed-masry/chartqa_with_t5"
    auto_download: true
    cache_dir: "models/chart_recognition"
    # 图表识别的替代方案
    fallback_models:
      - "microsoft/trocr-base-chart"
      


# 模型性能配置
model_performance:
  # GPU内存管理
  gpu_memory:
    # 模型显存占用限制（MB）
    max_memory_per_model: 2048
    # 显存清理策略
    cleanup_strategy: "lru"
    # 自动卸载不活跃模型
    auto_unload_inactive: true
    
  # CPU推理优化
  cpu_optimization:
    # 线程数（auto为自动检测）
    num_threads: "auto"
    # 使用优化库
    use_optimized_kernels: true
    
  # 模型量化（减少内存使用）
  quantization:
    # 是否启用量化
    enabled: false
    # 量化类型（int8, fp16）
    type: "int8" 