# 提示词配置文件 - 管理项目中使用的所有提示词

# 文档解析提示词
document_parsing:
  # 实体提取提示词
  entity_extraction: |
    请从以下文本中提取重要的实体信息，包括人名、组织名、地名、产品名、专业术语等。
    
    文本内容：
    {text}
    
    请以JSON格式返回实体列表，每个实体包含名称、类型和在文本中的位置：
    {
      "entities": [
        {"name": "实体名", "type": "实体类型", "position": "起始位置-结束位置"}
      ]
    }
  
  # 关系提取提示词
  relation_extraction: |
    请从以下文本中提取实体之间的关系。
    
    文本内容：
    {text}
    
    已识别的实体：
    {entities}
    
    请以JSON格式返回关系列表：
    {
      "relations": [
        {"subject": "主体实体", "predicate": "关系类型", "object": "客体实体", "confidence": 0.95}
      ]
    }

# 表格分析提示词
table_analysis:
  # 表格内容总结
  table_summary: |
    请分析以下表格内容，提供一个简洁的总结，说明表格的主要信息和结构。
    
    表格内容：
    {table_content}
    
    请提供：
    1. 表格主题
    2. 主要数据类型
    3. 关键发现
    4. 数据趋势（如果有）

# 图像分析提示词
image_analysis:
  # 图像描述
  image_description: |
    请详细描述这张图像的内容，包括：
    1. 图像类型（照片、图表、示意图等）
    2. 主要元素和对象
    3. 颜色、布局等视觉特征
    4. 图像传达的信息或意图
    
    请用中文详细描述。

# 图表分析提示词
chart_analysis:
  # 图表解读
  chart_interpretation: |
    请分析这个图表，提供以下信息：
    1. 图表类型（柱状图、折线图、饼图等）
    2. 坐标轴和标签
    3. 数据趋势和模式
    4. 关键数据点
    5. 图表要传达的主要信息
    
    图表数据：
    {chart_data}

# 智能检索提示词
intelligent_search:
  # 检索结果整合
  result_integration: |
    基于以下检索到的相关信息，请回答用户的问题。请确保答案准确、完整，并引用相关的文档内容。
    
    用户问题：
    {question}
    
    检索到的相关信息：
    {retrieved_info}
    
    请提供一个结构化的回答，包括：
    1. 直接回答
    2. 支持证据
    3. 相关文档引用

  # 多轮对话
  conversation_context: |
    这是一个多轮对话，请根据对话历史和当前问题提供回答。
    
    对话历史：
    {conversation_history}
    
    当前问题：
    {current_question}
    
    相关文档信息：
    {document_info}
    
    请保持对话的连贯性，提供准确和有用的回答。

# 文档摘要提示词
document_summary:
  # 章节摘要
  section_summary: |
    请为以下文档章节提供一个简洁的摘要，突出主要观点和关键信息。
    
    章节标题：{title}
    章节内容：{content}
    
    摘要应该：
    1. 控制在200字以内
    2. 包含主要观点
    3. 保持原文的核心意思

  # 全文摘要
  document_summary: |
    请为整篇文档提供一个全面的摘要，包括：
    1. 文档主题
    2. 主要章节内容
    3. 关键结论
    4. 重要数据或发现
    
    文档内容：
    {document_content}
    
    摘要长度控制在500字以内。 